In [1]:
import pandas as pd
#pip install yfinance
import yfinance as yf

In [2]:
#Getting data from Yahoo Finance
#########################################################################################
df = yf.download("AAPL",
                 start = "2011-01-01",
                 end = "2021-12-31",
                 progress = False)

In [3]:
print(f"Downloaded {len(df)} rows of data.")
df

Downloaded 2768 rows of data.

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2011-01-03,11.630000,11.795000,11.601429,11.770357,10.017966,445138400
2011-01-04,11.872857,11.875000,11.719643,11.831786,10.070248,309080800
2011-01-05,11.769643,11.940714,11.767857,11.928571,10.152629,255519600
2011-01-06,11.954286,11.973214,11.889286,11.918929,10.144419,300428800
2011-01-07,11.928214,12.012500,11.853571,12.004286,10.217069,311931200
...,...,...,...,...,...,...
2021-12-23,175.850006,176.850006,175.270004,176.279999,174.995605,68356600
2021-12-27,177.089996,180.419998,177.070007,180.330002,179.016113,74919600
2021-12-28,180.160004,181.330002,178.529999,179.289993,177.983688,79144300
2021-12-29,179.330002,180.630005,178.139999,179.380005,178.073029,62348900
2021-12-30,179.470001,180.570007,178.089996,178.199997,176.901642,59773000

In [4]:
appl_data = yf.Ticker("AAPL")#another way of downloading the data
appl_data.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-01-17 00:00:00-05:00,134.624449,137.080690,133.925519,135.732758,63646600,0.00,0.0
2023-01-18 00:00:00-05:00,136.611422,138.398686,134.824142,135.003876,69672800,0.00,0.0
2023-01-19 00:00:00-05:00,133.875593,136.042283,133.566069,135.063782,58280400,0.00,0.0
2023-01-20 00:00:00-05:00,135.073758,137.809586,134.015376,137.659805,79972200,0.00,0.0
2023-01-23 00:00:00-05:00,137.909435,143.101520,137.689769,140.894882,81760300,0.00,0.0
2023-01-24 00:00:00-05:00,140.096097,142.941758,140.086117,142.312714,66435100,0.00,0.0
2023-01-25 00:00:00-05:00,140.675215,142.212861,138.598384,141.643738,65799300,0.00,0.0
2023-01-26 00:00:00-05:00,142.951735,144.030091,141.683667,143.740540,54105100,0.00,0.0
2023-01-27 00:00:00-05:00,142.941753,147.005541,142.861874,145.707520,70492800,0.00,0.0
2023-01-30 00:00:00-05:00,144.739016,145.328113,142.632232,142.781998,64015300,0.00,0.0
2023-01-31 00:00:00-05:00,142.482450,144.119949,142.063092,144.070023,65874500,0.00,0.0
2023-02-01 00:00:00-05:00,143.750517,146.386491,141.104563,145.208282,77663600,0.00,0.0
2023-02-02 00:00:00-05:00,148.673001,150.949524,147.944119,150.590088,118339000,0.00,0.0
2023-02-03 00:00:00-05:00,147.804328,157.140080,147.604636,154.264465,154279900,0.00,0.0
2023-02-06 00:00:00-05:00,152.337419,152.866610,150.550139,151.498688,69858300,0.00,0.0
2023-02-07 00:00:00-05:00,150.410349,154.993348,150.410349,154.414230,83322600,0.00,0.0
2023-02-08 00:00:00-05:00,153.645419,154.344349,150.939544,151.688400,64120100,0.00,0.0
2023-02-09 00:00:00-05:00,153.545567,154.094731,150.190688,150.639999,56007100,0.00,0.0
2023-02-10 00:00:00-05:00,149.460007,151.339996,149.220001,151.009995,57409100,0.23,0.0
2023-02-13 00:00:00-05:00,150.949997,154.259995,150.919998,153.850006,62199000,0.00,0.0
2023-02-14 00:00:00-05:00,152.119995,153.770004,150.860001,153.199997,61707600,0.00,0.0
2023-02-15 00:00:00-05:00,153.110001,155.500000,152.880005,155.330002,65669300,0.00,0.0
2023-02-16 00:00:00-05:00,153.509995,156.330002,153.350006,153.710007,68031000,0.00,0.0
2023-02-17 00:00:00-05:00,152.350006,153.000000,151.370102,151.750000,26766102,0.00,0.0

In [5]:
#########################################################################################

In [6]:
#Getting data from Nasdaq Data Link
#before downloading the data, we need to create an account at https://data.nasdaq.com/,
#authenticate our email address and find our API key in our profile
import pandas as pd
# pip install nasdaq-data-link
import nasdaqdatalink

In [7]:
nasdaqdatalink.ApiConfig.api_key = "YOUR_KEY_HERE"

In [8]:
df = nasdaqdatalink.get(dataset = "WIKI/AAPL",
                        start_date = "2011-01-01",
                        end_date = "2021-12-31")

LimitExceededError: (Status 429) (Nasdaq Data Link Error QELx06) You have exceeded the API speed limit and your account has temporaly been disabled.  Please contact clientsuccess@nasdaq.com for more information.

In [9]:
print(f"Downloaded {len(df)} rows of data.")
df.head()

Downloaded 2768 rows of data.

                 Open       High        Low      Close  Adj Close     Volume
Date
2011-01-03  11.630000  11.795000  11.601429  11.770357  10.017966  445138400
2011-01-04  11.872857  11.875000  11.719643  11.831786  10.070248  309080800
2011-01-05  11.769643  11.940714  11.767857  11.928571  10.152629  255519600
2011-01-06  11.954286  11.973214  11.889286  11.918929  10.144419  300428800
2011-01-07  11.928214  12.012500  11.853571  12.004286  10.217069  311931200

In [ ]:
#another way
COLUMNS = ["ticker", "date", "adj_close"]
df = nasdaqdatalink.get_table("WIKE/PRICES",
                              ticker = ["AAPL","MSFT","INTC"],
                              qopts = {"columns":COLUMNS},
                              date = {"gte":"2011-01-01","lte":"2021-12-31"},
                              paginate = True)
df.head()

In [ ]:
df = df.set_index("date")
df_wide = df.pivot(columns = "ticker")
df_wide.head()

In [ ]:
#################################################################################
#getting data from Intrinio
#register API key: https://intrinio.com
#(https://docs.intrinio.com/developer-sandbox) this link has some information about 
#sandbox API key(the free one)
import intrinio_sdk as intrinio
import pandas as pd

In [ ]:
intrinio.ApiClient().set_api_key("YOUR_OWN_KEY")
# now many functions have to be used with subscription, so the next codes may get faults with a free account
security_api = intrinio.SecurityApi()# use our own API key

In [ ]:
#request the data
r = security_api.get_security_stock_prices(
    identifier="AAPL",
    start_date="2011-01-01",
    end_date="2021-12-31",
    frequency="daily",
    page_size=10000
)

In [ ]:
df = {
    pd.DataFrame(r.stock_prices_dict)
    .sort_values("date")
    .set_index("date")
}
print(f"Downloaded {df.shape[0]} rows of data")
df.head()
# https://docs.intrinio.com/developer-sandbox this link can tell us
#what data we can download for free

In [ ]:
security_api.get_security_realtime_price("KO")

In [ ]:
#Download news articles related to Coca-Cola
r = intrinio.CompanyApi().get_company_news(
    identifier = "KO",
    page_size = 100
)
df = pd.DataFrame(r.news_dict)
df.head()

In [ ]:
#Search for companies connected to the search phrase
r = intrinio.CompanyApi().recognize_company("Intel")
df = pd.DataFrame(r.companies_dict)
df

In [ ]:
#Get Coca-Colaâ€™s intraday stock prices
response = (
    security_api.get_security_intraday_prices(
        identifier = "KO",
        start_date = "2021-01-02",
        end_date = "2021-01-05",
        page_size = 1000
    )
)
df = pd.DataFrame(response.intraday_prices_dict)
df

In [ ]:
#Get Coca-Colaâ€™s latest earnings record
r = security_api.get_security_latest_earnings_record(identifier="KO")
print(r)

In [ ]:
#################################################################################
#getting data from Alpha Vantage
# register at https://www.alphavantage.co/support/#api-key to obtain API key
#S60126HPP6W0UBHX
from alpha_vantage.cryptocurrencies import CryptoCurrencies
ALPHA_VANTAGE_API_KEY = "S60126HPP6W0UBHX"
crypto_api = CryptoCurrencies(key = ALPHA_VANTAGE_API_KEY, output_format = "pandas")

In [ ]:
data, meta_data = crypto_api.get_digital_currency_daily(
    symbol="BTC",
    market="EUR"
)
#meta_data object contains some useful information about the details of the query
#the data DataFrame contains all the requested information
meta_data

In [ ]:
data

In [ ]:
crypto_api.get_digital_currency_exchange_rate(
    from_currency="BTC",
    to_currency="USD"
)[0].transpose()

In [ ]:
#another way of accessing API
import requests
import pandas as pd
from io import BytesIO

In [ ]:
AV_API_URL = "https://www.alphavantage.co/query"
parameters = {
 "function": "CRYPTO_INTRADAY",
 "symbol": "ETH",
 "market": "USD",
 "interval": "30min",
 "outputsize": "full",
 "apikey": "S60126HPP6W0UBHX"
}
r = requests.get(AV_API_URL, params=parameters)
data = r.json()
'''data
   {'Information': 'Thank you for using Alpha Vantage!
   This is a premium endpoint.
   You may subscribe to any of the premium plans 
   at https://www.alphavantage.co/premium/ to instantly unlock all premium endpoints'}
'''
df = (
 pd.DataFrame(data["header"])
 .transpose()
)
df

In [ ]:
#download the upcoming earnings announcements within the next three months
parameters = {
    "function":"EARNINGS_CALENDAR",
    "horizon":"3month",
    "apikey": ALPHA_VANTAGE_API_KEY
}
r = requests.get(AV_API_URL, params = parameters)
pd.read_csv(BytesIO(r.content))
#the output of r.content is a bytes object containing the output of the query as text
# using the BytesIO class from the io module can mimic a normal file in-memory

In [ ]:
########################################################################################
#getting data from coingecko//completely free!!!
from pycoingecko import CoinGeckoAPI
from datetime import datetime
import pandas as pd
cg = CoinGeckoAPI()

In [ ]:
ohlc = cg.get_coin_ohlc_by_id(
    id = "bitcoin", vs_currency = "usd", days = "14"
)
ohlc_df = pd.DataFrame(ohlc)
ohlc_df.columns = ["date", "open", "high", "low", "close"]
ohlc_df["date"] = pd.to_datetime(ohlc_df["date"], unit = "ms")
ohlc_df#we must predefine number of days
#varying frequency: 
#30 minutes for requests of 1 or 2 days
#4 hours between 3 and 30 days
#every 4 days above 30 days

In [ ]:
#get the top 7 trending coins
trending_coins = cg.get_search_trending()
(
    pd.DataFrame([coin["item"] for coin in trending_coins["coins"]])
    .drop(columns=["thumb","small","large"])
)
#double braces means the return of the front function is a function which needs parameters
#in the back brace

In [ ]:
#get bitcoin's current price in USD
cg.get_price(ids="bitcoin", vs_currencies="usd")
#documentation  https://github.com/man-c/pycoingecko.